import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e3e2e2",
        "surface-container-highest": "#353535",
        "surface": "#131313",
        "on-secondary-fixed-variant": "#920022",
        "secondary-fixed-dim": "#ffb3b3",
        "on-surface": "#e2e2e2",
        "primary-fixed": "#ffdad4",
        "metallic-steel": "#A9A9A9",
        "hazard-glow": "rgba(220, 20, 60, 0.4)",
        "surface-tint": "#ffb4a8",
        "outline": "#aa8984",
        "inverse-primary": "#b52619",
        "evidence-paper": "#D2C9B1",
        "on-secondary-fixed": "#40000a",
        "surface-dim": "#131313",
        "primary-fixed-dim": "#ffb4a8",
        "error-container": "#93000a",
        "secondary-container": "#d10235",
        "inverse-on-surface": "#303030",
        "on-tertiary-container": "#aeaeae",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-primary-fixed-variant": "#920703",
        "primary": "#ffb4a8",
        "surface-bright": "#393939",
        "on-primary": "#690000",
        "on-secondary": "#680015",
        "on-secondary-container": "#ffe1e1",
        "tertiary": "#c7c6c6",
        "surface-variant": "#353535",
        "surface-container-low": "#1b1b1b",
        "on-tertiary-fixed": "#1a1c1c",
        "outline-variant": "#5a403c",
        "inverse-surface": "#e2e2e2",
        "on-error-container": "#ffdad6",
        "crimson-glare": "#DC143C",
        "on-primary-fixed": "#410000",
        "secondary-fixed": "#ffdad9",
        "tertiary-container": "#414242",
        "error": "#ffb4ab",
        "on-primary-container": "#ff907f",
        "primary-container": "#8b0000",
        "on-tertiary-fixed-variant": "#464747",
        "background": "#131313",
        "on-tertiary": "#2f3131",
        "surface-container-high": "#2a2a2a",
        "void-black": "#000000",
        "on-background": "#e2e2e2",
        "blood-red": "#8B0000",
        "secondary": "#ffb3b3",
        "on-error": "#690005",
        "surface-container-lowest": "#0e0e0e",
        "on-surface-variant": "#e3beb8",
        "surface-container": "#1f1f1f"
      },
      backgroundImage: {
        'fog-overlay': 'linear-gradient(to bottom, rgba(19, 19, 19, 0) 0%, rgba(19, 19, 19, 0.8) 100%)',
        'metallic-texture': 'url("data:image/svg+xml,%3Csvg viewBox=%220 0 200 200%22 xmlns=%22http://www.w3.org/2000/svg%22%3E%3Cfilter id=%22noiseFilter%22%3E%3CfeTurbulence type=%22fractalNoise%22 baseFrequency=%220.65%22 numOctaves=%223%22 stitchTiles=%22stitch%22/%3E%3C/filter%3E%3Crect width=%22100%25%22 height=%22100%25%22 filter=%22url(%23noiseFilter)%22 opacity=%220.05%22/%3E%3C/svg%3E")',
      },
      fontFamily: {
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["var(--font-creepster)", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-md": ["var(--font-courier-prime)", "monospace"],
        "headline-xl": ["var(--font-nosifer)", "sans-serif"],
        "display-lg": ["var(--font-nosifer)", "sans-serif"],
        "body-lg": ["var(--font-courier-prime)", "monospace"]
      },
    },
  },
  plugins: [],
};
export default config;
